// Codegen Implementation - generiert pro Permutation eine C++23-Modul-Quelle
// + CMake-Target.

#include "codegen.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>

namespace comdare::builder::codegen {

void CodegenEngine::generate_module(
    xml::PermutationEntry const& ce_perm,
    xml::PermutationEntry const& sa_perm,
    xml::PermutationEntry const& alloc_perm,
    std::uint64_t fingerprint) const
{
    std::filesystem::create_directories(opts_.output_root);

    // 1. Generate C++23 module source
    std::ofstream src{module_source_path(fingerprint)};
    src << "// AUTO-GENERATED by CacheEngineBuilder Phase 6.4\n";
    src << "// Permutation fingerprint: 0x" << std::hex << std::setw(16) << std::setfill('0')
        << fingerprint << "\n";
    src << "// CacheEngine perm:    " << ce_perm.id << "\n";
    src << "// SearchAlgorithm:     " << sa_perm.id << "\n";
    src << "// Allocator perm:      " << alloc_perm.id << "\n\n";
    src << "#include <cache_engine/abi/module_abi_v1.hpp>\n\n";
    src << "#if defined(_WIN32)\n";
    src << "  #define COMDARE_MODULE_EXPORT __declspec(dllexport)\n";
    src << "#elif defined(__GNUC__) || defined(__clang__)\n";
    src << "  #define COMDARE_MODULE_EXPORT __attribute__((visibility(\"default\")))\n";
    src << "#else\n";
    src << "  #define COMDARE_MODULE_EXPORT\n";
    src << "#endif\n\n";
    src << "namespace {\n";
    src << "struct PermutationModule_v1 {};\n";
    src << "void* create_instance(comdare_cache_engine_v1* /*engine*/) { return new PermutationModule_v1{}; }\n";
    src << "void  destroy_instance(void* inst) { delete static_cast<PermutationModule_v1*>(inst); }\n";
    src << "void  run_workload(void* /*inst*/, comdare_workload_descriptor_v1 const* /*workload*/,\n";
    src << "                   comdare_measurement_record_v1* out_record) {\n";
    src << "    if (out_record) { *out_record = {}; out_record->version = COMDARE_ABI_VERSION; }\n";
    src << "}\n";
    src << "void  pull_live_counters(void* /*inst*/, comdare_hw_counters_v1* out) {\n";
    src << "    if (out) { *out = {}; }\n";
    src << "}\n";
    src << "comdare_permutation_module_v1 const k_module = {\n";
    src << "    .abi_version             = COMDARE_ABI_VERSION,\n";
    src << "    .permutation_fingerprint = 0x" << std::hex << fingerprint << std::dec << "ULL,\n";
    src << "    .create_instance         = create_instance,\n";
    src << "    .destroy_instance        = destroy_instance,\n";
    src << "    .run_workload            = run_workload,\n";
    src << "    .pull_live_counters      = pull_live_counters,\n";
    src << "};\n";
    src << "}  // anonymous namespace\n\n";
    src << "extern \"C\" COMDARE_MODULE_EXPORT comdare_permutation_module_v1 const*\n";
    src << "comdare_get_module_v1(void) {\n";
    src << "    return &k_module;\n";
    src << "}\n";

    // 2. Generate CMakeLists.txt for this module
    // WICHTIG: CMake interpretiert Strings mit Backslashes als Escape-Sequenzen.
    // Auch unter Windows muessen Pfade in CMake-Strings mit Forward-Slash geschrieben werden.
    auto to_cmake_path = [](std::filesystem::path const& p) {
        std::string s = p.generic_string();  // konvertiert Backslashes zu Slashes
        return s;
    };

    std::ofstream cm{module_cmake_path(fingerprint)};
    cm << "# AUTO-GENERATED by CacheEngineBuilder Phase 6.4\n";
    cm << "add_library(comdare_perm_" << std::hex << fingerprint << " SHARED\n";
    cm << "    \"${CMAKE_CURRENT_LIST_DIR}/module_" << std::hex << fingerprint << ".cpp\"\n";
    cm << ")\n";
    cm << "target_include_directories(comdare_perm_" << std::hex << fingerprint << " PRIVATE\n";
    cm << "    \"" << to_cmake_path(opts_.comdare_root) << "/cache_engine/include\"\n";
    cm << ")\n";
    cm << "target_compile_features(comdare_perm_" << std::hex << fingerprint << " PRIVATE cxx_std_23)\n";
    cm << "set_target_properties(comdare_perm_" << std::hex << fingerprint
       << " PROPERTIES OUTPUT_NAME \"comdare_perm_" << std::hex << fingerprint << "\")\n";
}

std::filesystem::path CodegenEngine::module_source_path(std::uint64_t fingerprint) const {
    std::ostringstream name;
    name << "module_" << std::hex << fingerprint << ".cpp";
    return opts_.output_root / name.str();
}

std::filesystem::path CodegenEngine::module_cmake_path(std::uint64_t fingerprint) const {
    std::ostringstream name;
    name << "module_" << std::hex << fingerprint << "_CMakeLists.txt";
    return opts_.output_root / name.str();
}

std::filesystem::path CodegenEngine::aggregate_cmake_path() const {
    return opts_.output_root / "CMakeLists.txt";
}

// REV 7.6 V9.3 — Modul aus AlgorithmProfile generieren
// REV 7.6 V17.1 — optionale Template-Substitution: wenn unter
// templates/<profile.id>_body.hpp.template ein Body-Template existiert,
// wird es per #include eingebunden statt des Skelett-Bodys.
void CodegenEngine::generate_module_from_profile(
    xml::AlgorithmProfile const& profile,
    std::uint64_t fingerprint) const
{
    std::filesystem::create_directories(opts_.output_root);

    // V17.1 — Template-Lookup
    auto const template_dir = opts_.comdare_root /
        "cache_engine" / "builder" / "codegen" / "templates";
    auto const template_path = template_dir / (profile.id + "_body.hpp.template");
    bool const has_template = std::filesystem::exists(template_path);

    std::ostringstream src_name;
    src_name << "module_profile_" << profile.id << "_" << std::hex << fingerprint << ".cpp";
    auto src_path = opts_.output_root / src_name.str();

    std::ofstream src{src_path};
    src << "// AUTO-GENERATED by CodegenEngine::generate_module_from_profile (V9.3 + V17.1)\n";
    src << "// Profile id   : " << profile.id << "\n";
    src << "// Paper-Ref    : " << profile.paper_ref << "\n";
    src << "// Fingerprint  : 0x" << std::hex << fingerprint << "\n";
    src << "// Template     : " << (has_template ? "yes" : "no (skelett body)") << "\n";
    src << "//\n// Achsen-Konfiguration:\n";
    for (auto const& [axis, value] : profile.axes) {
        src << "//   " << axis << " = " << value << "\n";
    }
    src << "//\n// Key/Value-Signatur:\n";
    src << "//   key_types   = " << profile.key_types << "\n";
    src << "//   value_types = " << profile.value_types << "\n\n";

    src << "#include <cache_engine/abi/module_abi_v1.hpp>\n";
    if (has_template) {
        // V17.1: Template-Body wird inline included (relativer Pfad, sodass
        // das generierte Modul zur Build-Zeit den Template-Header findet).
        src << "#include \"" << template_path.generic_string() << "\"\n";
    }
    src << "\n";
    src << "#if defined(_WIN32)\n";
    src << "  #define COMDARE_MODULE_EXPORT __declspec(dllexport)\n";
    src << "#elif defined(__GNUC__) || defined(__clang__)\n";
    src << "  #define COMDARE_MODULE_EXPORT __attribute__((visibility(\"default\")))\n";
    src << "#else\n";
    src << "  #define COMDARE_MODULE_EXPORT\n";
    src << "#endif\n\n";
    src << "namespace {\n";
    if (has_template) {
        // V17.1: Template stellt eine Body-Klasse `ProfileModuleBody` bereit.
        // Wir verwenden diese Klasse als Body — die Funktionen delegieren an sie.
        src << "// V17.1: Template-Body wird verwendet (siehe Include oben).\n";
        src << "// Erwartet: namespace comdare::cache_engine::builder::generated::ProfileModuleBody\n";
        src << "using TemplateBody = ::comdare::cache_engine::builder::generated::ProfileModuleBody;\n";
        src << "void* create_instance(comdare_cache_engine_v1* /*engine*/) { return new TemplateBody{}; }\n";
        src << "void  destroy_instance(void* inst) { delete static_cast<TemplateBody*>(inst); }\n";
        src << "void  run_workload(void* inst, comdare_workload_descriptor_v1 const* workload,\n";
        src << "                   comdare_measurement_record_v1* out_record) {\n";
        src << "    static_cast<TemplateBody*>(inst)->run_workload(workload, out_record);\n";
        src << "}\n";
        src << "void  pull_live_counters(void* inst, comdare_hw_counters_v1* out) {\n";
        src << "    static_cast<TemplateBody*>(inst)->pull_live_counters(out);\n";
        src << "}\n";
    } else {
        // Skelett-Body wie bisher (V9.3-Verhalten)
        src << "struct ProfileModule_v1 {\n";
        src << "    static constexpr char profile_id[] = \"" << profile.id << "\";\n";
        src << "    static constexpr char paper_ref[]  = \"" << profile.paper_ref << "\";\n";
        src << "};\n";
        src << "void* create_instance(comdare_cache_engine_v1* /*engine*/) { return new ProfileModule_v1{}; }\n";
        src << "void  destroy_instance(void* inst) { delete static_cast<ProfileModule_v1*>(inst); }\n";
        src << "void  run_workload(void* /*inst*/, comdare_workload_descriptor_v1 const* /*workload*/,\n";
        src << "                   comdare_measurement_record_v1* out_record) {\n";
        src << "    if (out_record) { *out_record = {}; out_record->version = COMDARE_ABI_VERSION; }\n";
        src << "}\n";
        src << "void  pull_live_counters(void* /*inst*/, comdare_hw_counters_v1* out) {\n";
        src << "    if (out) { *out = {}; }\n";
        src << "}\n";
    }
    src << "comdare_permutation_module_v1 const k_module = {\n";
    src << "    .abi_version             = COMDARE_ABI_VERSION,\n";
    src << "    .permutation_fingerprint = 0x" << std::hex << fingerprint << std::dec << "ULL,\n";
    src << "    .create_instance         = create_instance,\n";
    src << "    .destroy_instance        = destroy_instance,\n";
    src << "    .run_workload            = run_workload,\n";
    src << "    .pull_live_counters      = pull_live_counters,\n";
    src << "};\n";
    src << "}  // anonymous namespace\n\n";
    src << "extern \"C\" COMDARE_MODULE_EXPORT comdare_permutation_module_v1 const*\n";
    src << "comdare_get_module_v1(void) {\n";
    src << "    return &k_module;\n";
    src << "}\n";

    // CMakeLists pro Profil-Modul
    auto to_cmake_path = [](std::filesystem::path const& p) {
        return p.generic_string();
    };
    std::ostringstream cm_name;
    cm_name << "module_profile_" << profile.id << "_" << std::hex << fingerprint << "_CMakeLists.txt";
    auto cm_path = opts_.output_root / cm_name.str();

    std::ofstream cm{cm_path};
    cm << "# AUTO-GENERATED by CodegenEngine::generate_module_from_profile (V9.3)\n";
    cm << "# Profile: " << profile.id << " (" << profile.paper_ref << ")\n";
    auto target = std::string{"comdare_perm_profile_"} + profile.id + "_" +
                  [&] { std::ostringstream o; o << std::hex << fingerprint; return o.str(); }();
    cm << "add_library(" << target << " SHARED\n";
    cm << "    \"${CMAKE_CURRENT_LIST_DIR}/" << src_name.str() << "\"\n";
    cm << ")\n";
    cm << "target_include_directories(" << target << " PRIVATE\n";
    cm << "    \"" << to_cmake_path(opts_.comdare_root) << "/cache_engine/include\"\n";
    cm << ")\n";
    cm << "target_compile_features(" << target << " PRIVATE cxx_std_23)\n";
    cm << "set_target_properties(" << target
       << " PROPERTIES OUTPUT_NAME \"" << target << "\")\n";
}

void CodegenEngine::generate_aggregate_cmake(std::span<std::uint64_t const> fingerprints) const {
    std::filesystem::create_directories(opts_.output_root);
    std::ofstream cm{aggregate_cmake_path()};

    cm << "# AUTO-GENERATED Aggregator by CacheEngineBuilder Phase 7.2.A\n";
    cm << "# Aggregator fuer " << fingerprints.size() << " Permutationen.\n";
    cm << "cmake_minimum_required(VERSION 3.28)\n";
    cm << "project(comdare_permutations LANGUAGES CXX)\n\n";
    cm << "set(CMAKE_CXX_STANDARD 23)\n";
    cm << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
    cm << "set(CMAKE_CXX_EXTENSIONS OFF)\n\n";
    cm << "# Default-Position-Independent-Code fuer SHARED-Modul-Binaries (REV 7 ABI v1)\n";
    cm << "set(CMAKE_POSITION_INDEPENDENT_CODE ON)\n\n";

    // Master-Aggregator-Target: baut alle Permutationen
    cm << "add_custom_target(comdare_all_permutations ALL\n";
    cm << "    COMMENT \"Building all " << fingerprints.size() << " Comdare permutation modules\")\n\n";

    cm << "# Per-Permutation Include + Dependency-Hook\n";
    for (auto fp : fingerprints) {
        std::ostringstream fp_hex;
        fp_hex << std::hex << fp;
        cm << "include(\"${CMAKE_CURRENT_LIST_DIR}/module_" << fp_hex.str()
           << "_CMakeLists.txt\")\n";
        cm << "add_dependencies(comdare_all_permutations comdare_perm_"
           << fp_hex.str() << ")\n";
    }

    cm << "\n# Status-Line am Configure-Ende\n";
    cm << "message(STATUS \"Comdare Permutations Aggregator: " << fingerprints.size()
       << " module(s) registered\")\n";
}

}  // namespace comdare::builder::codegen
