// Codegen Implementation - generiert pro Permutation eine C++23-Modul-Quelle
// + CMake-Target.

#include "codegen.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>

namespace comdare::builder::codegen {

void CodegenEngine::generate_module(
    xml::PermutationEntry const& ce_perm,
    xml::PermutationEntry const& sa_perm,
    xml::PermutationEntry const& alloc_perm,
    std::uint64_t fingerprint) const
{
    std::filesystem::create_directories(opts_.output_root);

    // 1. Generate C++23 module source
    std::ofstream src{module_source_path(fingerprint)};
    src << "// AUTO-GENERATED by CacheEngineBuilder Phase 6.4\n";
    src << "// Permutation fingerprint: 0x" << std::hex << std::setw(16) << std::setfill('0')
        << fingerprint << "\n";
    src << "// CacheEngine perm:    " << ce_perm.id << "\n";
    src << "// SearchAlgorithm:     " << sa_perm.id << "\n";
    src << "// Allocator perm:      " << alloc_perm.id << "\n\n";
    src << "#include <cache_engine/abi/module_abi_v1.hpp>\n\n";
    src << "namespace {\n";
    src << "struct PermutationModule_v1 {};\n";
    src << "void* create_instance(comdare_cache_engine_v1* /*engine*/) { return new PermutationModule_v1{}; }\n";
    src << "void  destroy_instance(void* inst) { delete static_cast<PermutationModule_v1*>(inst); }\n";
    src << "void  run_workload(void* /*inst*/, comdare_workload_descriptor_v1 const* /*workload*/,\n";
    src << "                   comdare_measurement_record_v1* out_record) {\n";
    src << "    if (out_record) { *out_record = {}; out_record->version = COMDARE_ABI_VERSION; }\n";
    src << "}\n";
    src << "void  pull_live_counters(void* /*inst*/, comdare_hw_counters_v1* out) {\n";
    src << "    if (out) { *out = {}; }\n";
    src << "}\n";
    src << "comdare_permutation_module_v1 const k_module = {\n";
    src << "    .abi_version             = COMDARE_ABI_VERSION,\n";
    src << "    .permutation_fingerprint = 0x" << std::hex << fingerprint << std::dec << "ULL,\n";
    src << "    .create_instance         = create_instance,\n";
    src << "    .destroy_instance        = destroy_instance,\n";
    src << "    .run_workload            = run_workload,\n";
    src << "    .pull_live_counters      = pull_live_counters,\n";
    src << "};\n";
    src << "}  // anonymous namespace\n\n";
    src << "extern \"C\" comdare_permutation_module_v1 const* comdare_get_module_v1(void) {\n";
    src << "    return &k_module;\n";
    src << "}\n";

    // 2. Generate CMakeLists.txt for this module
    std::ofstream cm{module_cmake_path(fingerprint)};
    cm << "# AUTO-GENERATED by CacheEngineBuilder Phase 6.4\n";
    cm << "add_library(comdare_perm_" << std::hex << fingerprint << " SHARED\n";
    cm << "    module_" << std::hex << fingerprint << ".cpp\n";
    cm << ")\n";
    cm << "target_include_directories(comdare_perm_" << std::hex << fingerprint << " PRIVATE\n";
    cm << "    \"" << opts_.comdare_root.string() << "/cache_engine/include\"\n";
    cm << ")\n";
    cm << "target_compile_features(comdare_perm_" << std::hex << fingerprint << " PRIVATE cxx_std_23)\n";
    cm << "set_target_properties(comdare_perm_" << std::hex << fingerprint
       << " PROPERTIES OUTPUT_NAME \"comdare_perm_" << std::hex << fingerprint << "\")\n";
}

std::filesystem::path CodegenEngine::module_source_path(std::uint64_t fingerprint) const {
    std::ostringstream name;
    name << "module_" << std::hex << fingerprint << ".cpp";
    return opts_.output_root / name.str();
}

std::filesystem::path CodegenEngine::module_cmake_path(std::uint64_t fingerprint) const {
    std::ostringstream name;
    name << "module_" << std::hex << fingerprint << "_CMakeLists.txt";
    return opts_.output_root / name.str();
}

}  // namespace comdare::builder::codegen
