#pragma once
// V41.F.6.1.R5.F — anatomy_codegen_tool Library-API
//
// User-Direktive 2026-05-27 (Doku 14 §47.8):
// R5.F C++-Tool das CMake-Composition-Snippet generiert. Schliesst die Luecke
// zwischen Compile-Time PermutationEngine und Build-System CMake.
//
// Pilot-Strategie: hardcoded CompositionDescriptor-Tabelle der 11 known
// Compositions (6 CE-Reimpl + 5 PaperBinding) statt PermutationEngine-Iteration.
// Voll-Integration mit `SearchAlgorithmPermutationEngine::for_each_composition_type`
// folgt in R5.G (2-Pass-Build: Tool zuerst, dann CMake-Configure mit Tool-Output).
//
// @doku docs/architektur/14_achsen_komposition_organ_metapher.md §48
// @task #710 V41.F.6.1.R5.F

#include "../../anatomy/composition_concept.hpp"

#include <cstdint>
#include <filesystem>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace comdare::cache_engine::builder::codegen_tool {

// ─────────────────────────────────────────────────────────────────────────────
// CompositionDescriptor — eine bekannte Composition fuer das Tool
// ─────────────────────────────────────────────────────────────────────────────

struct CompositionDescriptor {
    std::string_view short_name;     ///< CLI-friendly, z.B. "art"
    std::string_view cpp_type_name;  ///< fully-qualified C++ Type-Name
    std::string_view header_include; ///< Include-Pfad relativ zu libs/cache_engine/
};

// ─────────────────────────────────────────────────────────────────────────────
// Tabelle aller bekannten Compositions (Stand R5.F)
// ─────────────────────────────────────────────────────────────────────────────

/// kKnownCompositions — 11 Eintraege (6 CE-Reimpl + 5 PaperBinding).
[[nodiscard]] std::span<CompositionDescriptor const> known_compositions() noexcept;

// ─────────────────────────────────────────────────────────────────────────────
// Selektion + Look-up
// ─────────────────────────────────────────────────────────────────────────────

/// find_composition(name) — Lookup ueber short_name. Liefert nullptr wenn unbekannt.
[[nodiscard]] CompositionDescriptor const* find_composition(std::string_view short_name) noexcept;

/// select_compositions(csv_names) — Parsen comma-separated short-name-Liste,
/// liefert Vektor von Descriptor-Pointer. Leerer csv -> alle known_compositions.
///
/// Bei unbekanntem Namen: Eintrag fehlt, `unknown_out` (wenn non-null) wird
/// mit dem unbekannten Namen gefuellt.
[[nodiscard]] std::vector<CompositionDescriptor const*>
select_compositions(std::string_view csv_names, std::vector<std::string>* unknown_out = nullptr);

// ─────────────────────────────────────────────────────────────────────────────
// CMake-Snippet-Output
// ─────────────────────────────────────────────────────────────────────────────

/// LibraryType — passend zu comdare_codegen_anatomy_module_list LIBRARY_TYPE.
enum class LibraryType : std::uint8_t { Shared = 0, Static = 1 };

[[nodiscard]] constexpr std::string_view library_type_name(LibraryType t) noexcept {
    return (t == LibraryType::Static) ? "STATIC" : "SHARED";
}

/// parse_library_type(s) — String -> LibraryType. nullptr bei Unbekannt.
[[nodiscard]] LibraryType const* parse_library_type(std::string_view s) noexcept;

// ─────────────────────────────────────────────────────────────────────────────
// R5.G — descriptor_from_composition<C>() Template (Compile-Time-Extraktion)
// ─────────────────────────────────────────────────────────────────────────────

/// descriptor_from_composition<C>() — extrahiert CompositionDescriptor aus
/// einem Compile-Time Composition-Type C. Pflicht: C erfuellt
/// `HasCompositionLocation` Concept (cpp_type_name + header_include vorhanden).
///
/// short_name wird aus dem `C::name`-Member uebernommen (z.B. "ArtComposition").
/// Wenn der CLI-Tool-User einen anderen short_name will, baut er den
/// CompositionDescriptor manuell mit anderen Defaults.
///
/// Verwendung:
/// ```cpp
/// using ArtComp = ::comdare::cache_engine::compositions::ArtComposition;
/// constexpr auto desc = descriptor_from_composition<ArtComp>();
/// static_assert(desc.cpp_type_name ==
///     "::comdare::cache_engine::compositions::ArtComposition");
/// ```
///
/// Bridge zwischen Compile-Time `for_each_composition_type` (R5.C.B) und
/// Build-System CMake-Codegen (R5.D.2 + R5.D.3 + R5.F).
template <::comdare::cache_engine::anatomy::HasCompositionLocation C>
[[nodiscard]] constexpr CompositionDescriptor descriptor_from_composition() noexcept {
    return CompositionDescriptor{C::name, C::cpp_type_name, C::header_include};
}

/// write_cmake_snippet(path, selected, lib_type) — Schreibt CMake-Snippet das
/// die Variablen COMDARE_PERMUTATION_LIBRARY_TYPE + COMDARE_PERMUTATION_COMPOSITIONS
/// setzt. Format passend zu comdare_codegen_anatomy_module_list().
///
/// Beispiel-Output:
/// ```cmake
/// # Auto-generated by comdare-anatomy-codegen-tool — DO NOT EDIT
/// set(COMDARE_PERMUTATION_LIBRARY_TYPE "SHARED")
/// set(COMDARE_PERMUTATION_COMPOSITIONS
///     "::comdare::cache_engine::compositions::ArtComposition|compositions/art_reference.hpp"
///     "::comdare::cache_engine::compositions::HotComposition|compositions/hot_reference.hpp"
/// )
/// ```
///
/// Liefert true bei Erfolg, false wenn File nicht geschrieben werden konnte.
[[nodiscard]] bool write_cmake_snippet(std::filesystem::path const&                  output_path,
                                       std::span<CompositionDescriptor const* const> selected, LibraryType lib_type);

} // namespace comdare::cache_engine::builder::codegen_tool
