// V41.F.6.1.P1 Phase B — is_original_validator Pre-Build-Tool
//
// @stand V41.F.6.1.P1 Phase B Pilot mimalloc
// @reference [[compile-time-only-no-runtime]] Memory
// @reference [[paper-original-code-pattern]] Memory
//
// **PRE-BUILD-TOOL** zur Erzeugung von constexpr Header-Files mit hardcoded
// is_original-Booleans. Wird zur BUILD-TIME (nicht Runtime!) ausgefuehrt;
// Output-Header wird vom Cache-Engine-Wrapper includiert.
//
// **User-Direktive [[compile-time-only-no-runtime]]:** Runtime-SHA-Berechnung
// ist VERBOTEN fuer Latenz-kritische Suchalgorithmen. Workaround: dieses Tool
// rechnet SHA zur Build-Zeit + emittiert constexpr Header. Cache-Engine selbst
// hat ZERO Runtime-Overhead — `is_original_<fn>()` ist hardcoded literal.
//
// Verwendung (von CMake, comdare_generate_is_original_header()):
//
//   is_original_validator \
//       --source     path/to/legacy_code/paper_xy/alloc.c \
//       --function   allocate \
//       --expected   5f8b3a... (64-char hex) \
//       --output     ${CMAKE_BINARY_DIR}/generated/.../wrapper_is_original.hpp \
//       --namespace  comdare::cache_engine::allocator::axis_06_allocator::generated
//
// Output-Header:
//   #pragma once
//   namespace <namespace> {
//   inline constexpr bool kIsOriginal_<function> = true|false;
//   }
//
// Mehrere Funktionen pro Header: Tool kann iterativ aufgerufen werden (append-mode)
// oder mit JSON-Manifest erweitert (Phase B.2 — heute nur single-function mode).

#include "sha256/ctsha.hpp"

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;
namespace ctsha = ::comdare::cache_engine::sha256;

namespace {

void print_usage(char const* argv0) {
    std::cerr << "Usage: " << argv0 << " --source <file> --function <name> "
              << "--expected <sha-hex> --output <header.hpp> --namespace <ns>\n";
}

std::vector<std::uint8_t> read_file_bytes(fs::path const& p) {
    std::ifstream ifs(p, std::ios::binary | std::ios::ate);
    if (!ifs) {
        std::cerr << "ERROR: cannot open " << p.string() << "\n";
        std::exit(2);
    }
    auto size = static_cast<std::size_t>(ifs.tellg());
    ifs.seekg(0);
    std::vector<std::uint8_t> bytes(size);
    if (size > 0) {
        ifs.read(reinterpret_cast<char*>(bytes.data()), static_cast<std::streamsize>(size));
    }
    return bytes;
}

std::string runtime_to_hex(ctsha::Digest const& d) {
    static char const* const kHex = "0123456789abcdef";
    std::string s(64, '0');
    for (std::size_t i = 0; i < 32; ++i) {
        s[2 * i + 0] = kHex[(d[i] >> 4) & 0x0f];
        s[2 * i + 1] = kHex[d[i] & 0x0f];
    }
    return s;
}

ctsha::Digest sha256_runtime(std::span<const std::uint8_t> data) {
    // Hinweis: ctsha::sha256 IST constexpr; hier nutzen wir es zur Runtime im Tool.
    // Tool-Runtime ist Build-Time-OK (NICHT Cache-Engine-Hot-Path).
    return ctsha::detail::sha256_bytes(data.data(), data.size());
}

}  // namespace

int main(int argc, char** argv) {
    std::string source_path;
    std::string function_name;
    std::string expected_hex;
    std::string output_path;
    std::string namespace_name;

    for (int i = 1; i < argc; ++i) {
        std::string_view arg = argv[i];
        if      (arg == "--source"    && i + 1 < argc) source_path    = argv[++i];
        else if (arg == "--function"  && i + 1 < argc) function_name  = argv[++i];
        else if (arg == "--expected"  && i + 1 < argc) expected_hex   = argv[++i];
        else if (arg == "--output"    && i + 1 < argc) output_path    = argv[++i];
        else if (arg == "--namespace" && i + 1 < argc) namespace_name = argv[++i];
        else {
            print_usage(argv[0]);
            return 1;
        }
    }
    if (source_path.empty() || function_name.empty() || expected_hex.empty()
        || output_path.empty() || namespace_name.empty()) {
        print_usage(argv[0]);
        return 1;
    }
    if (expected_hex.size() != 64) {
        std::cerr << "ERROR: expected SHA must be 64 hex chars (got " << expected_hex.size() << ")\n";
        return 1;
    }

    auto bytes = read_file_bytes(source_path);
    auto digest = sha256_runtime(std::span<const std::uint8_t>{bytes.data(), bytes.size()});
    auto computed_hex = runtime_to_hex(digest);

    bool is_original = (computed_hex == expected_hex);

    fs::create_directories(fs::path(output_path).parent_path());
    std::ofstream ofs(output_path);
    if (!ofs) {
        std::cerr << "ERROR: cannot open output " << output_path << "\n";
        return 2;
    }
    ofs << "#pragma once\n";
    ofs << "// AUTO-GENERATED by is_original_validator — DO NOT EDIT\n";
    ofs << "// Source:   " << source_path << "\n";
    ofs << "// Function: " << function_name << "\n";
    ofs << "// Expected: " << expected_hex << "\n";
    ofs << "// Computed: " << computed_hex << "\n";
    ofs << "// Match:    " << (is_original ? "true" : "false") << "\n";
    ofs << "\n";
    ofs << "namespace " << namespace_name << " {\n";
    ofs << "inline constexpr bool kIsOriginal_" << function_name << " = "
        << (is_original ? "true" : "false") << ";\n";
    ofs << "}  // namespace\n";

    std::cout << "is_original_validator: " << function_name << " "
              << (is_original ? "PASS" : "MISMATCH")
              << " (computed=" << computed_hex.substr(0, 12) << "...)\n";

    return 0;  // exit 0 auch bei Mismatch — Wrapper-Tests fangen das ab
}
