#pragma once
// V41.F.6.1 R5.G — adhoc_emitter: schreibt pro Permutation eines PermutationEngine ein KOMPILIERBARES
// Modul-.cpp (Umbrella-Include + COMDARE_DEFINE_ANATOMY_MODULE_ADHOC mit den 17 FQ-Achsen-Typen).
//
// Das ist die wiederverwendbare Kern-Funktion des R5.G-Auto-Emitters: aus einer Engine über den
// gemergten Permutations-Raum (for_each_composition_type) werden alle Modul-.cpp generiert, die dann
// per CMake als Permutations-DLLs gebaut werden. Bausteine (type_name + ADHOC-Makro + Umbrella) sind
// einzeln verifiziert; diese Datei kombiniert sie zur File-Emission.

#include "type_name.hpp"

#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

namespace comdare::cache_engine::builder::codegen {

/// adhoc_macro_args<C>() — die 17 FQ-Achsen-Typ-Namen einer Composition C als Komma-getrennter Block
/// (Argument für COMDARE_DEFINE_ANATOMY_MODULE_ADHOC). Reihenfolge = AdHocComposition<T0..T16>.
template <class C>
[[nodiscard]] std::string adhoc_macro_args() {
    std::string s;
    auto add = [&](std::string_view t) { if (!s.empty()) s += ",\n    "; s += t; };
    add(type_name<typename C::search_algo>());
    add(type_name<typename C::cache_traversal>());
    add(type_name<typename C::mapping>());
    add(type_name<typename C::path_compression>());
    add(type_name<typename C::node_type>());
    add(type_name<typename C::memory_layout>());
    add(type_name<typename C::allocator>());
    add(type_name<typename C::prefetch>());
    add(type_name<typename C::concurrency>());
    add(type_name<typename C::serialization>());
    add(type_name<typename C::telemetry>());
    add(type_name<typename C::value_handle>());
    add(type_name<typename C::isa>());
    add(type_name<typename C::index_organization>());
    add(type_name<typename C::io_dispatch>());
    add(type_name<typename C::migration_policy>());
    add(type_name<typename C::filter>());
    return s;
}

/// emit_adhoc_modules<Engine>(out_dir) — schreibt für JEDE Permutation des Engine ein Modul-.cpp nach
/// out_dir (Dateiname comdare_anatomy_perm_auto_<idx>.cpp) und liefert die geschriebenen Pfade.
/// Jedes .cpp ist standalone kompilierbar (nur Umbrella-Include + ADHOC-Makro).
template <class Engine>
[[nodiscard]] std::vector<std::filesystem::path>
emit_adhoc_modules(std::filesystem::path const& out_dir) {
    std::error_code ec;
    std::filesystem::create_directories(out_dir, ec);
    std::vector<std::filesystem::path> files;
    int idx = 0;
    Engine::for_each_composition_type([&]<class C>() {
        std::filesystem::path const f =
            out_dir / ("comdare_anatomy_perm_auto_" + std::to_string(idx) + ".cpp");
        std::ofstream out(f, std::ios::trunc);
        out << "// AUTO-GENERATED by R5.G adhoc_emitter — Permutation " << idx << " — DO NOT EDIT\n"
            << "#include <builder/codegen/all_axes_umbrella.hpp>\n\n"
            << "COMDARE_DEFINE_ANATOMY_MODULE_ADHOC(\n    "
            << adhoc_macro_args<C>() << ")\n";
        files.push_back(f);
        ++idx;
    });
    return files;
}

}  // namespace comdare::cache_engine::builder::codegen
