#pragma once
// 234-V-a (2026-07-07, User-GO Option A) -- SHAPED-Emission als SIBLING zum R5.G-adhoc_emitter.
//
// BEWUSST eigener Header (nicht in adhoc_emitter.hpp): der organ_for!=void-Filter braucht
// <axes/lookup/composable/organ_for_search_algo.hpp> und damit den Pool-Store-Include-Baum inkl.
// generierter axis_*_flags.hpp. Der Plain-Emitter wird von Konsumenten OHNE diese Include-Wurzeln
// gebaut (tools-Facade, ceb_generator) -- ihr Include-Graph bleibt hier byte-identisch unangetastet.
// Konsumenten dieses Headers (Tests, spaeter der Baum-Pfad in 234-V-b) bringen die Achsen-Wurzeln mit.
//
// DEFAULT-OFF: kein Aufrufer im Standard-Emissions-Pfad (emit_adhoc_modules / apps main.cpp
// unveraendert); die Verdrahtung in den Experiment-Baum ist 234-V-b.

#include "adhoc_emitter.hpp"

#include <axes/lookup/composable/organ_for_search_algo.hpp> // Filter: exakt die Adapter-Ableitung (pool_family_)

#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace comdare::cache_engine::builder::codegen {

/// render_adhoc_module_source_shaped -- der kompilierbare Modul-.cpp-Quelltext einer SHAPED-Permutation.
/// Identisches Textformat wie render_adhoc_module_source, aber mit COMDARE_DEFINE_ANATOMY_MODULE_ADHOC_SHAPED
/// und dem FQ-Shape-Typ als ERSTEM Argument (BUILDVARIANT-Praezedenz: benannte Args zuerst). Der Shape ist
/// Adapter-Traeger, KEIN 18. Slot -- die 17 Achsen-Args bleiben unveraendert (INC-2d).
/// REVIEW-FIX (Critical-1, 07.07.): shape_include wird MIT-emittiert -- die Umbrella-Closure erreicht nur den
/// Default-Shape der Familie (z.B. Kt4 via btree_node_pool_store.hpp:17); ohne expliziten Shape-Include waere
/// die generierte TU fuer jeden Nicht-Default-Shape NICHT kompilierbar. Der Aufrufer liefert den Include-Pfad,
/// der den Shape deklariert (btree_order: die Registry topics/nodes/axis_btree_order/
/// axis_btree_order_registry.hpp -- deklariert ALLE Kt-Shapes).
[[nodiscard]] inline std::string render_adhoc_module_source_shaped(int idx, std::string_view shape_fq,
                                                                   std::string_view shape_include,
                                                                   std::string_view macro_args) {
    return "// AUTO-GENERATED by 234-V-a adhoc_emitter (SHAPED) -- Permutation " + std::to_string(idx) +
           " -- DO NOT EDIT\n"
           "#include <builder/codegen/all_axes_umbrella.hpp>\n"
           "#include <" +
           std::string{shape_include} +
           ">\n\n"
           "COMDARE_DEFINE_ANATOMY_MODULE_ADHOC_SHAPED(\n    " +
           strip_all_elaborated(shape_fq) + ",\n    " + std::string{macro_args} + ")\n";
}

/// emit_adhoc_modules_shaped<Engine, Shape>(out_dir, shape_include) -- schreibt fuer jede ORGAN-BACKED
/// Permutation des Engine (Filter: organ_for_search_algo_t<C::search_algo> != void -- exakt die Ableitung der
/// Adapter-Naht, abi_adapter.hpp pool_family_) ein SHAPED-Modul-.cpp. Familienfremde Kompositionen werden
/// NICHT emittiert (keine Scheinmultiplikation, Z.198-Disziplin). shape_include s. render-Doku (Critical-1).
template <class Engine, class Shape>
[[nodiscard]] std::vector<std::filesystem::path> emit_adhoc_modules_shaped(std::filesystem::path const& out_dir,
                                                                           std::string_view             shape_include) {
    std::error_code ec;
    std::filesystem::create_directories(out_dir, ec);
    std::vector<std::filesystem::path> files;
    int                                emitted = 0;
    Engine::for_each_composition_type([&]<class C>() {
        using OrganT = ::comdare::cache_engine::lookup::composable::organ_for_search_algo_t<typename C::search_algo>;
        if constexpr (!std::is_same_v<OrganT, void>) {
            std::filesystem::path const f =
                out_dir / ("comdare_anatomy_perm_auto_shaped_" + std::to_string(emitted) + ".cpp");
            std::ofstream out(f, std::ios::trunc);
            out << render_adhoc_module_source_shaped(emitted, type_name<Shape>(), shape_include, adhoc_macro_args<C>());
            files.push_back(f);
            ++emitted;
        }
    });
    return files;
}

} // namespace comdare::cache_engine::builder::codegen
